name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Get sugarcube
        run: |
          mkdir storyformats
          cd storyformats
          curl -L https://github.com/tmedwards/sugarcube-2/releases/download/v2.36.1/sugarcube-2.36.1-for-twine-2.1-local.zip > sugarcube-2.zip
          unzip sugarcube-2.zip
          cd ..

      - name: build tweego
        run: |
          git clone https://github.com/tmedwards/tweego.git
          cd tweego
          git checkout master
          go get
          go install
          go build
          cd ..

      - name: build game
        run: |
          mkdir dist
          ./tweego/tweego "Who Stole My Sausages_.twee" -o dist/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload directory
          path: './dist'
