name: Build

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: reformat twee file
        run: |
          python format.py

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Get sugarcube
        run: |
          mkdir storyformats
          cd storyformats
          curl -L https://github.com/tmedwards/sugarcube-2/releases/download/v2.36.1/sugarcube-2.36.1-for-twine-2.1-local.zip > sugarcube-2.zip
          unzip sugarcube-2.zip
          cd ..

      - name: build tweego
        run: |
          git clone https://github.com/tmedwards/tweego.git
          cd tweego
          git checkout master
          go get
          go install
          go build
          cd ..

      - name: build game
        run: |
          mkdir dist
          mv img dist/img
          mv audio dist/audio
          ./tweego/tweego "output.twee" "new-sausage-script.js" "sausage-style.css" -o dist/index.html

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: dist

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload directory
          path: 'dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

