name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: build game
        run: |
          git clone https://github.com/tmedwards/tweego.git .
          git checkout master
          go get
          go install
          go build
          tweego "Who Stole My Sausages_.twee" -o dist/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload directory
          path: './dist'
